### PR TITLE
[FEATURE] Restrict masking backgrounds from png images

### PR DESCRIPTION
**Pull request by barclayd**

### CODE REVIEW

**Comment by dreampiggy** [comment]
Seems like you can solve the PNG background using the `onDisappear` or `SDWebImage's Image Transformer`, did you really have to provide such an API for this limited case?

Transformer: https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#image-transformer-50

**Comment by barclayd** [comment]
Hi, yes you’re right. I wasn’t quite sure how to access the underlying UIImage within the current API - Image Transformer looks like the right place to access it, thanks very much!

I accidentally raised the PR against your main branch so please feel free to ignore it.

**Comment by dreampiggy** [comment]
The underlying `UIImage` can be grabed by the `.onSuccess` API from WebImage, or using someting like that Image Transformer feature, which is much more customizable and flexible.

**Comment by barclayd** [comment]
That’s excellent, thanks again and thank you for all the excellent work done on this library 😊

**Pull request closed without merging**
