### PR TITLE
Don't embed SDWebImage.framework in SDWebImageSwiftUI.framework

### PR DESCRIPTION
**Pull request by jonkan**
Solves https://github.com/SDWebImage/SDWebImageSwiftUI/issues/96

### CODE REVIEW

**Comment by dreampiggy** [comment]
Good catch.

But you only change the `SDWebImageSwiftUI iOS` framework target. There are 4 targets totally. The diff should looks like this:

image

**Comment by dreampiggy** [comment]
@jonkan Do I need to create another PR ? Or you fix it and commit again ?

I'll wait for reply until tomorrow, or I'll fix it by another PR.

**Comment by jonkan** [comment]
Ah sorry, forgot them. I'll fix.

**Comment by dreampiggy** [comment]
Fixed and released with SDWebImageSwiftUI v1.3.1. Thanks !

**Pull request merged**
