### PR TITLE
fix transition not working

### PR DESCRIPTION
**Pull request by wishWinds**
This will fix transition modifier not working. 
The side effect is transition will always animate even if image is load from memory or disk cache.

### CODE REVIEW

**Comment by dreampiggy** [comment]
I don't think add this into a ObservedObject is suitable...

The correct way maybe put this `withAnimation` into the `WebImage`'s return body of images

**Comment by wishWinds** [comment]
It may has no way to trigger animation within `onSuccess` callback. the `imageManager` are internal. and exposing the manager is not a good choice.
What I'm thinking is give a chance to tell the framework using animation when remote image Is come.
I'm thinking add a `enableAnimation` modifier to WebImage.
If you think this may be a right approach. I will make a new PR!

Thanks.

**Comment by zizooom** [comment]
Thank you

**Comment by aviwad** [comment]
any update? transition still broken

**Comment by alexfanatics** [comment]
I found a workaround here: https://github.com/SDWebImage/SDWebImageSwiftUI/issues/272

**Comment by aviwad** [comment]
why did you close the PR?

**Pull request closed without merging**
